### Issue token
POST http://localhost:3000/auth/token/issue
Content-Type: application/json

{
  "email": "harry.kane@kakaostyle.com",
  "password": "harry.kane"
}

### Refresh token
POST http://localhost:3000/auth/token/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDg3MWNlMi0xZTc4LTQ0MzEtYjI0OS1mN2I2MWQzYjBmZGIiLCJlbWFpbCI6ImhhcnJ5LmthbmVAa2FrYW9zdHlsZS5jb20iLCJpYXQiOjE2NzAxNjIzMDksImV4cCI6MTY3MDc2NzEwOX0.wlyYM9hE62dzgLBGrd4K_CAopFZfbwQmFjth9kg4Q-0

{
  "email": "harry.kane@kakaostyle.com",
  "password": "harry.kane"
}

### Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDg3MWNlMi0xZTc4LTQ0MzEtYjI0OS1mN2I2MWQzYjBmZGIiLCJlbWFpbCI6ImhhcnJ5LmthbmVAa2FrYW9zdHlsZS5jb20iLCJpYXQiOjE2NzAxNjIzMDksImV4cCI6MTY3MDc2NzEwOX0.wlyYM9hE62dzgLBGrd4K_CAopFZfbwQmFjth9kg4Q-0

{
  "email": "harry.kane@kakaostyle.com",
  "password": "harry.kane"
}
